apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: comhub.retry.5m
  namespace: kafka
  labels:
    strimzi.io/cluster: comhub
spec:
  partitions: 12
  replicas: 3
  config:
    # Third and final retry tier, 24h retention
    retention.ms: 86400000
